---
os: ubuntu
dist: xenial

language: python
python:
  - "2.7"
  - "3.6"

branches:
  only:
    - master

install:
  - sudo ./setup/ubuntu/deb_install
  - pip install -r ./setup/pip_requirements.txt
script: ./setup/ci/common/test.sh
