workspace(name = "external_data_pkg_test")

load("//:drake_path.bzl", "get_drake_path")

local_repository(
    name = "bazel_external_data_pkg",
    path = get_drake_path(__workspace_dir__),
)

load("//:repo_example.bzl", "add_repo_archive_repository")

add_repo_archive_repository()
